### ISSUE TITLE
`user` does not exist during the first phase of chef recipe

### ISSUE THREAD

**Issue by mbasset** [poise/application_git#3]
There appears to be an issue where the user does not exist during the first phase of the chef recipe. What happens is that the user (to be created during convergence) does yet exist and so when the script attempts to write the ssh wrapper it cannot because the user is not yet in the system.

```
================================================================================
         Recipe Compile Error in /tmp/kitchen/cookbooks/topics/recipes/deploy.rb
         ================================================================================

         ArgumentError
         -------------
         user deploy doesn't exist

         Cookbook Trace:
         ---------------
           /tmp/kitchen/cookbooks/application_git/files/halite_gem/poise_application_git/resource.rb:87:in `expand_path'
           /tmp/kitchen/cookbooks/application_git/files/halite_gem/poise_application_git/resource.rb:87:in `ssh_wrapper_path'
           /tmp/kitchen/cookbooks/application_git/files/halite_gem/poise_application_git/resource.rb:75:in `deploy_key'
           /tmp/kitchen/cookbooks/topics/recipes/deploy.rb:77:in `block (2 levels) in from_file'
           /tmp/kitchen/cookbooks/application/files/halite_gem/poise_application/resources/application.rb:182:in `instance_exec'
           /tmp/kitchen/cookbooks/application/files/halite_gem/poise_application/resources/application.rb:182:in `block (3 levels) in _rewire_dsl!'
           /tmp/kitchen/cookbooks/poise/files/halite_gem/poise/helpers/subresources/container.rb:150:in `instance_exec'
           /tmp/kitchen/cookbooks/poise/files/halite_gem/poise/helpers/subresources/container.rb:150:in `block (2 levels) in declare_resource'
           /tmp/kitchen/cookbooks/poise/files/halite_gem/poise/helpers/subresources/container.rb:140:in `block in declare_resource'
           /tmp/kitchen/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `instance_eval'
           /tmp/kitchen/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `subcontext_block'
           /tmp/kitchen/cookbooks/poise/files/halite_gem/poise/helpers/subresources/container.rb:121:in `declare_resource'
           /tmp/kitchen/cookbooks/application/files/halite_gem/poise_application/resources/application.rb:175:in `public_send'
           /tmp/kitchen/cookbooks/application/files/halite_gem/poise_application/resources/application.rb:175:in `block (2 levels) in _rewire_dsl!'
           /tmp/kitchen/cookbooks/topics/recipes/deploy.rb:72:in `block in from_file'
           /tmp/kitchen/cookbooks/topics/recipes/deploy.rb:64:in `from_file'

         Relevant File Content:
         ----------------------
         /tmp/kitchen/cookbooks/application_git/files/halite_gem/poise_application_git/resource.rb:

          80:      end
          81:  
          82:      # Default SSH wrapper path.
          83:      #
          84:      # @api private
          85:      # @return [String]
          86:      def ssh_wrapper_path
          87>>       @ssh_wrapper_path ||= ::File.expand_path("~#{user}/.ssh/ssh_wrapper_#{Zlib.crc32(name)}")
          88:      end
          89:  
        90:      # Guess if the deploy key is a local path or literal value.
          91:      #
          92:      # @api private

          94:      # @return [Boolean]
          95:      def deploy_key_is_local?(key=nil)
        96:        key ||= deploy_key
```

**Comment by fidel** [comment]
@mbasset to workaround this problem you need to create user in the compile phase.
https://docs.chef.io/resource_common.html#run-action

``` ruby
user 'fancy_user' do
  # ...
  action :nothing
end.run_action(:create)
```

**Comment by tomjrob** [comment]
Thanks @fidel, works a charm for a regular chef run. But, do you know if there is any way to get this workaround to play nice with chefspec?
